Burst handler improvements
westerndigitalcorporation/OmnixtendEndpoint pull request #9
Opened 2023-04-11 15:43 UTC by cahz

* Fix off by one bug in last signal in RMW/WriteBurstHandler
* Increase maximum size of write transfers and error when exceeding

2023-04-11 16:25 UTC, jahofmann commented on src/RMWBurstHandler.bsv
> +            if(last_cntr == fromInteger(valueOf(MaximumAXIBeats)) - 1) begin
Thanks for this. Looks good.

2023-04-11 16:25 UTC, jahofmann commented on src/WriteBurstHandler.bsv
> +            if(last_cntr == fromInteger(valueOf(MaximumAXIBeats)) - 1) begin
Same as above.

2023-04-11 16:28 UTC, jahofmann requested changes
I'd prefer if this function is more generic. The way it is done right now it might add unnecessary overhead in a pure OX/TL application.

2023-04-11 16:28 UTC, jahofmann commented on src/WriteBurstHandler.bsv
> +        if(beats > fromInteger(3*valueOf(MaximumAXIBeats))) begin
For the reader: This is needed as cahz has some additional data to transfer. The OmniXtend endpoint supports up to 8 kB transfers right now to align with Ethernet jumbo packets.

I wonder if this adds hardware in cases where we don't need it. We should consider a generic function instead. For instance, we could create a LUT using a for-loop to support all sizes.

2023-04-12 07:56 UTC, cahz commented on src/WriteBurstHandler.bsv
> +        if(beats > fromInteger(3*valueOf(MaximumAXIBeats))) begin
I will have a look at it

2023-04-14 08:52 UTC, cahz commented on src/WriteBurstHandler.bsv
> +        if(beats > fromInteger(3*valueOf(MaximumAXIBeats))) begin
I have pushed an update. A first look at synthesis results don't show an increased overhead.

2023-04-14 16:16 UTC, jahofmann approved these changes
Thanks for the generalized version.

2023-04-14 16:17 UTC, merged